### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [vaibhav999garg/nodejs#2]
Hi,<br><br>url : https://github.com/vaibhav999garg/nodejs/blob/9991c5e7be837680621e129c356e698d3f2eed7d/learn_play.js <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by vaibhav999garg** [comment]
Thank you
Committed it by mistake.
Thanks again🤗

**Comment by shaybenb** [comment]
any time my frind, 
this is what i do 👍 

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
